# [helpers]

# all platforms
[base.files]
atuin = "~/.config/atuin"
broot = "~/.config/broot"
claude = "~/.claude"
gitui = "~/.config/gitui"
"git/.gitconfig" = "~/.gitconfig"
"git/.gitignore_global" = "~/.gitignore_global"
helix = "~/.config/helix"
"config/helix-ignore" = "~/.config/.ignore"
jj = "~/.config/jj"
jjui = "~/.config/jjui"
kanata = "~/.config/kanata"
markdown-oxide = "~/.config/moxide"
nushell = "~/.config/nushell"
synapse = "~/.config/synapse"
tongo = "~/.config/tongo"
wezterm = "~/.config/wezterm"
yazi = "~/.config/yazi"
zellij = "~/.config/zellij"

# macos only
[mac.files]

# linux only
[linux.files]
hypr = "~/.config/hypr"
waybar = "~/.config/waybar"
wofi = "~/.config/wofi"

# work only 
[work.files]
